name: Re Panza Brain - Daily Scan 327

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scanner
        run: python main.py
        env:
          LK_EMAIL: ${{ secrets.LK_EMAIL }}
          LK_PASS_HASH: ${{ secrets.LK_PASS_HASH }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "RePanzaBot"
          git add database_classificamondo327.json
          git commit -m "📊 Update Classifica Mondo 327 [$(date)]" || echo "No changes"
          git push
